#!/usr/bin/env bash
# Installs Nginx

# Update package lists
sudo apt-get update

# Install nginx
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
# Test nginx response
sudo bash -c 'echo "Hello World!" > /var/www/html/index.html'

# Restart nginx
service nginx restart
