#!/usr/bin/env bash
# Installs Nginx

# Update package lists
sudo apt-get update

# Install nginx
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
# Test nginx response
sudo bash -c 'echo "Hello World!" > /etc/nginx/html/index.html'
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html;
    location /redirect_me {
        return 301 https://twitter.com/Emmanue17280546;
    }
}" > /etc/nginx/sites-available/default

# Restart nginx
service nginx restart
