#!/usr/bin/env bash
# Installs Nginx

# Update package lists
sudo apt-get update

# Install nginx
sudo apt-get install -y nginx
service nginx start
mkdir /etc/nginx/html
sudo ufw allow 'Nginx HTTP'
# Test nginx response
echo "Hello World!" > /etc/nginx/html/index.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html;
    location /redirect_me {
        return 301 https://twitter.com/Emmanue17280546;
    }
    error_page 404 /404.html;
    location = /404.html{
        root /etc/nginx/html;
        internal;
    }
}" > /etc/nginx/sites-available/default

# Restart nginx
service nginx restart 
