#!/usr/bin/env bash
#Bash script that:
#Creates the file /var/run/myscript.pid
#Deletes the file /var/run/myscript.pid

terminator() {
  rm /var/run/myscript.pid
  exit
}

echo "$$" > /var/run/myscript.pid

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && terminator' SIGTERM
  trap 'terminator' SIGQUITgit 
done
