#!/usr/bin/env bash
#Bash script that displays Best School 10 times but for the 9th say Hi.

count=1

while [ $count -le 10 ]
do
  if [ $count -eq 10 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  ((count++))
done
